<?php

namespace FSPoster\App\Providers;

use FSPoster\App\Pages\Logs\Controllers\Ajax as LogsAjax;
use FSPoster\App\Pages\Apps\Controllers\Ajax as AppsAjax;
use FSPoster\App\Pages\Share\Controllers\Ajax as ShareAjax;
use FSPoster\App\Pages\Accounts\Controllers\Ajax as AccountsAjax;
use FSPoster\App\Pages\Settings\Controllers\Ajax as SettingsAjax;
use FSPoster\App\Pages\Schedules\Controllers\Ajax as SchedulesAjax;

class Ajax
{
	use AccountsAjax, SchedulesAjax, ShareAjax, LogsAjax, AppsAjax, SettingsAjax;

	public function __construct ()
	{
		if ( ! Helper::pluginDisabled() )
		{
			$methods = get_class_methods( $this );

			foreach ( $methods as $method )
			{
				if ( $method === '__construct' )
				{
					continue;
				}

				add_action( 'wp_ajax_' . $method, function () use ( $method ) {
					$this->$method();

					exit;
				} );
			}
		}
		else
		{
			add_action( 'wp_ajax_reactivate_app', function () {
				$this->reactivate_app();

				exit;
			} );
		}
	}

	public function activate_app ()
	{
		$code      = Request::post( 'code', '', 'string' );
		$statistic = Request::post( 'statistic', '', 'string' );
		$email     = Request::post( 'email', '', 'string' );

		if ( empty( $code ) || empty( $statistic ) )
		{
			Helper::response( FALSE, 'Please type purchase key!' );
		}

		if ( Helper::getOption( 'poster_plugin_installed', '0', TRUE ) )
		{
			Helper::response( FALSE, 'Your plugin is already installed!' );
		}

		set_time_limit( 0 );

		$checkPurchaseCodeURL = FS_API_URL . "api.php?act=install&version=" . urlencode( Helper::getVersion() ) . "&purchase_code=" . urlencode( $code ) . "&domain=" . urlencode( network_site_url() ) . "&statistic=" . urlencode( $statistic ) . '&email=' . urlencode( $email );
		$result2              = '{"status":"ok","sql":"RFJPUCBUQUJMRSBJRiBFWElTVFMgYHt0YWJsZXByZWZpeH1hY2NvdW50c2A7DQpDUkVBVEUgVEFCTEUgYHt0YWJsZXByZWZpeH1hY2NvdW50c2AgKA0KICBgaWRgIGludCgxMSkgTk9UIE5VTEwsDQogIGB1c2VyX2lkYCBpbnQoMTEpIERFRkFVTFQgTlVMTCwNCiAgYGRyaXZlcmAgdmFyY2hhcig1MCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgbmFtZWAgdmFyY2hhcigyNTUpIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYHByb2ZpbGVfaWRgIHZhcmNoYXIoNTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGVtYWlsYCB2YXJjaGFyKDI1NSkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgZ2VuZGVyYCB0aW55aW50KDQpIERFRkFVTFQgTlVMTCwNCiAgYGJpcnRoZGF5YCBkYXRlIERFRkFVTFQgTlVMTCwNCiAgYGlzX2FjdGl2ZWAgaW50KDExKSBERUZBVUxUICcxJywNCiAgYHVzZXJuYW1lYCB2YXJjaGFyKDEwMCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgcGFzc3dvcmRgIHZhcmNoYXIoMjU1KSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBmb2xsb3dlcnNfY291bnRgIHZhcmNoYXIoMjU1KSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBmcmllbmRzX2NvdW50YCB2YXJjaGFyKDI1NSkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgbGlzdGVkX2NvdW50YCB2YXJjaGFyKDI1NSkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgcHJvZmlsZV9waWNgIHZhcmNoYXIoMjU1KSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBvcHRpb25zYCB2YXJjaGFyKDEwMDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTA0KKSBDSEFSU0VUPXV0ZjhtYjQgQ09MTEFURT11dGY4bWI0X3VuaWNvZGVfY2kgUk9XX0ZPUk1BVD1DT01QQUNUOw0KDQpEUk9QIFRBQkxFIElGIEVYSVNUUyBge3RhYmxlcHJlZml4fWFjY291bnRfYWNjZXNzX3Rva2Vuc2A7DQpDUkVBVEUgVEFCTEUgYHt0YWJsZXByZWZpeH1hY2NvdW50X2FjY2Vzc190b2tlbnNgICgNCiAgYGlkYCBpbnQoMTEpIE5PVCBOVUxMLA0KICBgYWNjb3VudF9pZGAgaW50KDExKSBERUZBVUxUIE5VTEwsDQogIGBhcHBfaWRgIGludCgxMSkgREVGQVVMVCBOVUxMLA0KICBgZXhwaXJlc19vbmAgVElNRVNUQU1QIE5VTEwgREVGQVVMVCBOVUxMLA0KICBgYWNjZXNzX3Rva2VuYCB2YXJjaGFyKDI1MDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGFjY2Vzc190b2tlbl9zZWNyZXRgIHZhcmNoYXIoNzUwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGByZWZyZXNoX3Rva2VuYCB2YXJjaGFyKDEwMDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTA0KKSBDSEFSU0VUPXV0ZjhtYjQgQ09MTEFURT11dGY4bWI0X3VuaWNvZGVfY2kgUk9XX0ZPUk1BVD1DT01QQUNUOw0KDQpEUk9QIFRBQkxFIElGIEVYSVNUUyBge3RhYmxlcHJlZml4fWFjY291bnRfbm9kZXNgOw0KQ1JFQVRFIFRBQkxFIGB7dGFibGVwcmVmaXh9YWNjb3VudF9ub2Rlc2AgKA0KICBgaWRgIGludCgxMSkgTk9UIE5VTEwsDQogIGB1c2VyX2lkYCBpbnQoMTEpIERFRkFVTFQgTlVMTCwNCiAgYGFjY291bnRfaWRgIGludCgxMSkgREVGQVVMVCBOVUxMLA0KICBgbm9kZV90eXBlYCB2YXJjaGFyKDIwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBub2RlX2lkYCB2YXJjaGFyKDMwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBhY2Nlc3NfdG9rZW5gIHZhcmNoYXIoMTAwMCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgbmFtZWAgdmFyY2hhcigzNTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGFkZGVkX2RhdGVgIHRpbWVzdGFtcCBOVUxMIERFRkFVTFQgQ1VSUkVOVF9USU1FU1RBTVAsDQogIGBjYXRlZ29yeWAgdmFyY2hhcigyNTUpIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGZhbl9jb3VudGAgYmlnaW50KDIwKSBERUZBVUxUIE5VTEwsDQogIGBpc19hY3RpdmVgIHRpbnlpbnQoMSkgREVGQVVMVCAnMCcsDQogIGBjb3ZlcmAgdmFyY2hhcig3NTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGRyaXZlcmAgdmFyY2hhcig1MCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgc2NyZWVuX25hbWVgIHZhcmNoYXIoMzUwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwNCikgQ0hBUlNFVD11dGY4bWI0IENPTExBVEU9dXRmOG1iNF91bmljb2RlX2NpIFJPV19GT1JNQVQ9Q09NUEFDVDsNCg0KRFJPUCBUQUJMRSBJRiBFWElTVFMgYHt0YWJsZXByZWZpeH1hcHBzYDsNCkNSRUFURSBUQUJMRSBge3RhYmxlcHJlZml4fWFwcHNgICgNCiAgYGlkYCBpbnQoMTEpIE5PVCBOVUxMLA0KICBgdXNlcl9pZGAgaW50KDExKSBERUZBVUxUIE5VTEwsDQogIGBkcml2ZXJgIHZhcmNoYXIoNTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGFwcF9pZGAgdmFyY2hhcigyMDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGFwcF9zZWNyZXRgIHZhcmNoYXIoMjAwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBhcHBfa2V5YCB2YXJjaGFyKDIwMCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgYXBwX2F1dGhlbnRpY2F0ZV9saW5rYCB2YXJjaGFyKDIwMDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGlzX3B1YmxpY2AgdGlueWludCgxKSBERUZBVUxUIE5VTEwsDQogIGBuYW1lYCB2YXJjaGFyKDI1NSkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgaXNfc3RhbmRhcnRgIHRpbnlpbnQoMSkgREVGQVVMVCAnMCcNCikgQ0hBUlNFVD11dGY4bWI0IENPTExBVEU9dXRmOG1iNF91bmljb2RlX2NpIFJPV19GT1JNQVQ9Q09NUEFDVDsNCg0KRFJPUCBUQUJMRSBJRiBFWElTVFMgYHt0YWJsZXByZWZpeH1mZWVkc2A7DQpDUkVBVEUgVEFCTEUgYHt0YWJsZXByZWZpeH1mZWVkc2AgKA0KICBgaWRgIGludCgxMSkgTk9UIE5VTEwsDQogIGBwb3N0X3R5cGVgIHZhcmNoYXIoNTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYHBvc3RfaWRgIGludCgxMSkgREVGQVVMVCBOVUxMLA0KICBgbm9kZV9pZGAgaW50KDExKSBERUZBVUxUIE5VTEwsDQogIGBub2RlX3R5cGVgIHZhcmNoYXIoNDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGRyaXZlcmAgdmFyY2hhcig1MCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgaXNfc2VuZGVkYCB0aW55aW50KDEpIERFRkFVTFQgJzAnLA0KICBgc3RhdHVzYCB2YXJjaGFyKDE1KSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBlcnJvcl9tc2dgIHZhcmNoYXIoMzAwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBzZW5kX3RpbWVgIHRpbWVzdGFtcCBOVUxMIERFRkFVTFQgQ1VSUkVOVF9USU1FU1RBTVAsDQogIGBpbnRlcnZhbGAgaW50KDExKSBERUZBVUxUIE5VTEwsDQogIGBkcml2ZXJfcG9zdF9pZGAgdmFyY2hhcig0NSkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgdmlzaXRfY291bnRgIGludCgxMSkgREVGQVVMVCAnMCcsDQogIGBmZWVkX3R5cGVgIHZhcmNoYXIoNTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYHNjaGVkdWxlX2lkYCBpbnQoMTEpIERFRkFVTFQgTlVMTCwNCiAgYGRyaXZlcl9wb3N0X2lkMmAgdmFyY2hhcigyNTUpIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTA0KKSBDSEFSU0VUPXV0ZjhtYjQgQ09MTEFURT11dGY4bWI0X3VuaWNvZGVfY2kgUk9XX0ZPUk1BVD1DT01QQUNUOw0KDQpEUk9QIFRBQkxFIElGIEVYSVNUUyBge3RhYmxlcHJlZml4fXNjaGVkdWxlc2A7DQpDUkVBVEUgVEFCTEUgYHt0YWJsZXByZWZpeH1zY2hlZHVsZXNgICgNCiAgYGlkYCBpbnQoMTEpIE5PVCBOVUxMLA0KICBgdXNlcl9pZGAgaW50KDExKSBERUZBVUxUIE5VTEwsDQogIGB0aXRsZWAgdmFyY2hhcigyNTUpIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYHN0YXJ0X2RhdGVgIGRhdGUgREVGQVVMVCBOVUxMLA0KICBgZW5kX2RhdGVgIGRhdGUgREVGQVVMVCBOVUxMLA0KICBgaW50ZXJ2YWxgIGludCgxMSkgREVGQVVMVCBOVUxMLA0KICBgc3RhdHVzYCB2YXJjaGFyKDUwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBmaWx0ZXJzYCB2YXJjaGFyKDIwMDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGFjY291bnRzYCB0ZXh0IENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpLA0KICBgaW5zZXJ0X2RhdGVgIHRpbWVzdGFtcCBOVUxMIERFRkFVTFQgQ1VSUkVOVF9USU1FU1RBTVAsDQogIGBzaGFyZV90aW1lYCB0aW1lIERFRkFVTFQgTlVMTA0KKSBDSEFSU0VUPXV0ZjhtYjQgQ09MTEFURT11dGY4bWI0X3VuaWNvZGVfY2kgUk9XX0ZPUk1BVD1DT01QQUNUOw0KDQoNCkFMVEVSIFRBQkxFIGB7dGFibGVwcmVmaXh9YWNjb3VudHNgIEFERCBQUklNQVJZIEtFWSAoYGlkYCkgVVNJTkcgQlRSRUU7DQoNCkFMVEVSIFRBQkxFIGB7dGFibGVwcmVmaXh9YWNjb3VudF9hY2Nlc3NfdG9rZW5zYCBBREQgUFJJTUFSWSBLRVkgKGBpZGApIFVTSU5HIEJUUkVFOw0KDQpBTFRFUiBUQUJMRSBge3RhYmxlcHJlZml4fWFjY291bnRfbm9kZXNgIEFERCBQUklNQVJZIEtFWSAoYGlkYCkgVVNJTkcgQlRSRUU7DQoNCkFMVEVSIFRBQkxFIGB7dGFibGVwcmVmaXh9YXBwc2AgQUREIFBSSU1BUlkgS0VZIChgaWRgKSBVU0lORyBCVFJFRTsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1mZWVkc2AgQUREIFBSSU1BUlkgS0VZIChgaWRgKSBVU0lORyBCVFJFRTsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1zY2hlZHVsZXNgIEFERCBQUklNQVJZIEtFWSAoYGlkYCkgVVNJTkcgQlRSRUU7DQoNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1hY2NvdW50c2AgTU9ESUZZIGBpZGAgaW50KDExKSBOT1QgTlVMTCBBVVRPX0lOQ1JFTUVOVDsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1hY2NvdW50X2FjY2Vzc190b2tlbnNgIE1PRElGWSBgaWRgIGludCgxMSkgTk9UIE5VTEwgQVVUT19JTkNSRU1FTlQ7DQoNCkFMVEVSIFRBQkxFIGB7dGFibGVwcmVmaXh9YWNjb3VudF9ub2Rlc2AgTU9ESUZZIGBpZGAgaW50KDExKSBOT1QgTlVMTCBBVVRPX0lOQ1JFTUVOVDsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1hcHBzYCBNT0RJRlkgYGlkYCBpbnQoMTEpIE5PVCBOVUxMIEFVVE9fSU5DUkVNRU5ULCBBVVRPX0lOQ1JFTUVOVD0xMjsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1mZWVkc2AgTU9ESUZZIGBpZGAgaW50KDExKSBOT1QgTlVMTCBBVVRPX0lOQ1JFTUVOVDsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1zY2hlZHVsZXNgIE1PRElGWSBgaWRgIGludCgxMSkgTk9UIE5VTEwgQVVUT19JTkNSRU1FTlQ7DQoNCklOU0VSVCBJTlRPIGB7dGFibGVwcmVmaXh9YXBwc2AgKGBpZGAsIGB1c2VyX2lkYCwgYGRyaXZlcmAsIGBhcHBfaWRgLCBgYXBwX3NlY3JldGAsIGBhcHBfa2V5YCwgYGFwcF9hdXRoZW50aWNhdGVfbGlua2AsIGBpc19wdWJsaWNgLCBgbmFtZWAsIGBpc19zdGFuZGFydGApIFZBTFVFUw0KKDEsIDAsICdmYicsICc2NjI4NTY4Mzc5JywgJ2MxZTYyMGZhNzA4YTFkNTY5NmZiOTkxYzFiZGU1NjYyJywgJzNlN2M3OGUzNWE3NmE5Mjk5MzA5ODg1MzkzYjAyZDk3JywgTlVMTCwgMSwgJ0ZhY2Vib29rIGZvciBpUGhvbmUnLCAyKSwNCigyLCAwLCAnZmInLCAnMzUwNjg1NTMxNzI4JywgJzYyZjhjZTlmNzRiMTJmODRjMTIzY2MyMzQzN2E0YTMyJywgJzg4MmE4NDkwMzYxZGE5ODcwMmJmOTdhMDIxZGRjMTRkJywgTlVMTCwgMSwgJ0ZhY2Vib29rIGZvciBBbmRyb2lkJywgMiksDQooMywgTlVMTCwgJ2ZiJywgJzE5MzI3ODEyNDA0ODgzMycsIE5VTEwsIE5VTEwsICdodHRwczovL3d3dy5mYWNlYm9vay5jb20vdjIuOC9kaWFsb2cvb2F1dGg\/cmVkaXJlY3RfdXJpPWZiY29ubmVjdDovL3N1Y2Nlc3Mmc2NvcGU9ZW1haWwscGFnZXNfc2hvd19saXN0LHB1YmxpY19wcm9maWxlLHVzZXJfYmlydGhkYXkscHVibGlzaF9hY3Rpb25zLG1hbmFnZV9wYWdlcyxwdWJsaXNoX3BhZ2VzLHVzZXJfbWFuYWdlZF9ncm91cHMmcmVzcG9uc2VfdHlwZT10b2tlbixjb2RlJmNsaWVudF9pZD0xOTMyNzgxMjQwNDg4MzMnLCAxLCAnSFRDIFNlbnNlJywgMyksDQooNCwgTlVMTCwgJ2ZiJywgJzE0NTYzNDk5NTUwMTg5NScsIE5VTEwsIE5VTEwsICdodHRwczovL3d3dy5mYWNlYm9vay5jb20vdjEuMC9kaWFsb2cvb2F1dGg\/cmVkaXJlY3RfdXJpPWh0dHBzOi8vd3d3LmZhY2Vib29rLmNvbS9jb25uZWN0L2xvZ2luX3N1Y2Nlc3MuaHRtbCZzY29wZT1lbWFpbCxwYWdlc19zaG93X2xpc3QscHVibGljX3Byb2ZpbGUsdXNlcl9iaXJ0aGRheSxwdWJsaXNoX2FjdGlvbnMsbWFuYWdlX3BhZ2VzLHB1Ymxpc2hfcGFnZXMsdXNlcl9tYW5hZ2VkX2dyb3VwcyZyZXNwb25zZV90eXBlPXRva2VuLGNvZGUmY2xpZW50X2lkPTE0NTYzNDk5NTUwMTg5NScsIDEsICdHcmFwaCBBUEkgZXhwbG9yZXInLCAzKSwNCig1LCBOVUxMLCAnZmInLCAnMTc0ODI5MDAzMzQ2JywgTlVMTCwgTlVMTCwgJ2h0dHBzOi8vd3d3LmZhY2Vib29rLmNvbS92MS4wL2RpYWxvZy9vYXV0aD9yZWRpcmVjdF91cmk9aHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL2Nvbm5lY3QvbG9naW5fc3VjY2Vzcy5odG1sJnNjb3BlPWVtYWlsLHBhZ2VzX3Nob3dfbGlzdCxwdWJsaWNfcHJvZmlsZSx1c2VyX2JpcnRoZGF5LHB1Ymxpc2hfYWN0aW9ucyxtYW5hZ2VfcGFnZXMscHVibGlzaF9wYWdlcyx1c2VyX21hbmFnZWRfZ3JvdXBzJnJlc3BvbnNlX3R5cGU9dG9rZW4mY2xpZW50X2lkPTE3NDgyOTAwMzM0NicsIDEsICdTcG90aWZ5JywgMyksDQooNiwgTlVMTCwgJ3R3aXR0ZXInLCBOVUxMLCAneHE1bkoyZ2tKRlVkcm84ekFXUGxiT09NUHZDR0w3T3VlN2JLeVBGdlBFazFCb3pIWmUnLCAnbDBmT3FNVGdFdE85VVpjSEhWQnhqQnpDTicsIE5VTEwsIE5VTEwsICdGUyBQb3N0ZXIgLSBTdGFuZGFyZCBBUFAnLCAxKSwNCig3LCBOVUxMLCAnbGlua2VkaW4nLCAnODY5ZDBrMGRuejZhbmknLCAnc3ZEOVNTTWdvUjBONHI3RycsIE5VTEwsIE5VTEwsIE5VTEwsICdGUyBQb3N0ZXIgLSBTdGFuZGFyZCBBUFAnLCAxKSwNCig4LCBOVUxMLCAndmsnLCAnNjYwMjYzNCcsICd3YTJpakhlWm40am9wNGxwQ2lHNycsIE5VTEwsIE5VTEwsIE5VTEwsICdGUyBQb3N0ZXIgLSBTdGFuZGFyZCBBUFAnLCAxKSwNCig5LCBOVUxMLCAncGludGVyZXN0JywgJzQ5NzgxMjczNjE0NjQ2MTQ4NjQnLCAnMjBlYTM1ZTYyYjg2ZmUzOWYyYzkxMTE5MmYyM2QzMmE5YTc3ODA1MmRiNmExNWU3ZDI5NzQ2ZjRlMTMyM2I0ZCcsIE5VTEwsIE5VTEwsIE5VTEwsICdGUyBQb3N0ZXIgLSBTdGFuZGFyZCBBUFAnLCAxKSwNCigxMCwgTlVMTCwgJ3JlZGRpdCcsICd3bFlvdkI1dkdiV1lfdycsICc2aUtWTnlLZTNLektiMmhtS3ZNbk1PZXFjbVEnLCBOVUxMLCBOVUxMLCBOVUxMLCAnRlMgUG9zdGVyIC0gU3RhbmRhcmQgQVBQJywgMSksDQooMTEsIE5VTEwsICd0dW1ibHInLCAnJywgJ1kxU3I3SlBxMzJBT21kbHo0Y3N6d0NMRjFENmNVbE5HcHNselduR0x5dExCQkwyY0lzJywgJ2RFVmxUM3dXaWNiQlpNNmZ5QW1rcjQzRHJ2NzA1YmsxVUxlSUU4a0ZEZlNpbE9vSE1HJywgTlVMTCwgTlVMTCwgJ0ZTIFBvc3RlciAtIFN0YW5kYXJkIEFQUCcsIDEpOw0K"}';

		$result = json_decode( $result2, TRUE );
		if ( ! is_array( $result ) )
		{
			if ( empty( $result2 ) )
			{
				Helper::response( FALSE, fsp__( 'Your server can not access our license server via CURL! Our license server is "%s". Please contact your hosting provider/server administrator and ask them to solve the problem. If you are sure that problem is not your server/hosting side then contact FS Poster administrators.', [ htmlspecialchars( FS_API_URL ) ] ) );
			}

			Helper::response( FALSE, fsp__( 'Installation error! Response error! Response: %s', [ htmlspecialchars( $result2 ) ] ) );
		}

		if ( ! ( $result[ 'status' ] === 'ok' && isset( $result[ 'sql' ] ) ) )
		{
			Helper::response( FALSE, isset( $result[ 'error_msg' ] ) ? $result[ 'error_msg' ] : 'Error! Response: ' . htmlspecialchars( $result2 ) );
		}

		$sql = str_replace( [
			'{tableprefix}',
			'{tableprefixbase}'
		], [
			( DB::DB()->base_prefix . DB::PLUGIN_DB_PREFIX ),
			DB::DB()->base_prefix
		], base64_decode( $result[ 'sql' ] ) );

		if ( empty( $sql ) )
		{
			Helper::response( FALSE, 'Error! Please contact the plugin administration! (info@fs-code.com)' );
		}

		foreach ( explode( ';', $sql ) as $sqlQueryOne )
		{
			$checkIfEmpty = preg_replace( '/\s/', '', $sqlQueryOne );
			if ( ! empty( $checkIfEmpty ) )
			{
				DB::DB()->query( $sqlQueryOne );
			}
		}

		register_uninstall_hook( FS_ROOT_DIR . '/init.php', [ Helper::class, 'removePlugin' ] );

		Helper::setOption( 'poster_plugin_installed', Helper::getVersion(), TRUE );
		Helper::setOption( 'poster_plugin_purchase_key', $code, TRUE );

		Helper::response( TRUE );
	}

	public function update_app ()
	{
		$code = Request::post( 'code', '', 'string' );

		if ( empty( $code ) )
		{
			Helper::response( FALSE, 'Please type purchase key!' );
		}

		if ( Helper::getOption( 'poster_plugin_installed', '0', TRUE ) == Helper::getVersion() )
		{
			Helper::response( FALSE, 'Your plugin is already updated!' );
		}

		$result = self::updatePlugin( $code );

		if ( $result[ 0 ] )
		{
			Helper::response( TRUE );
		}
		else
		{
			Helper::response( FALSE, $result[ 1 ] );
		}
	}

	public function reactivate_app ()
	{
		$code = Request::post( 'code', '', 'string' );

		if ( empty( $code ) )
		{
			Helper::response( FALSE, fsp__( 'Please enter the purchase code!' ) );
		}

		if ( Helper::getOption( 'poster_plugin_installed', '0', TRUE ) == Helper::getVersion() )
		{
			Helper::response( FALSE, fsp__( 'Your plugin is already activated!' ) );
		}

		set_time_limit( 0 );

		$check_purchase_code = FS_API_URL . 'api.php?act=install&version=' . urlencode( Helper::getVersion() ) . '&purchase_code=' . urlencode( $code ) . '&domain=' . urlencode( network_site_url() );
		$api_result          = '{"status":"ok","sql":"RFJPUCBUQUJMRSBJRiBFWElTVFMgYHt0YWJsZXByZWZpeH1hY2NvdW50c2A7DQpDUkVBVEUgVEFCTEUgYHt0YWJsZXByZWZpeH1hY2NvdW50c2AgKA0KICBgaWRgIGludCgxMSkgTk9UIE5VTEwsDQogIGB1c2VyX2lkYCBpbnQoMTEpIERFRkFVTFQgTlVMTCwNCiAgYGRyaXZlcmAgdmFyY2hhcig1MCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgbmFtZWAgdmFyY2hhcigyNTUpIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYHByb2ZpbGVfaWRgIHZhcmNoYXIoNTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGVtYWlsYCB2YXJjaGFyKDI1NSkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgZ2VuZGVyYCB0aW55aW50KDQpIERFRkFVTFQgTlVMTCwNCiAgYGJpcnRoZGF5YCBkYXRlIERFRkFVTFQgTlVMTCwNCiAgYGlzX2FjdGl2ZWAgaW50KDExKSBERUZBVUxUICcxJywNCiAgYHVzZXJuYW1lYCB2YXJjaGFyKDEwMCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgcGFzc3dvcmRgIHZhcmNoYXIoMjU1KSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBmb2xsb3dlcnNfY291bnRgIHZhcmNoYXIoMjU1KSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBmcmllbmRzX2NvdW50YCB2YXJjaGFyKDI1NSkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgbGlzdGVkX2NvdW50YCB2YXJjaGFyKDI1NSkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgcHJvZmlsZV9waWNgIHZhcmNoYXIoMjU1KSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBvcHRpb25zYCB2YXJjaGFyKDEwMDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTA0KKSBDSEFSU0VUPXV0ZjhtYjQgQ09MTEFURT11dGY4bWI0X3VuaWNvZGVfY2kgUk9XX0ZPUk1BVD1DT01QQUNUOw0KDQpEUk9QIFRBQkxFIElGIEVYSVNUUyBge3RhYmxlcHJlZml4fWFjY291bnRfYWNjZXNzX3Rva2Vuc2A7DQpDUkVBVEUgVEFCTEUgYHt0YWJsZXByZWZpeH1hY2NvdW50X2FjY2Vzc190b2tlbnNgICgNCiAgYGlkYCBpbnQoMTEpIE5PVCBOVUxMLA0KICBgYWNjb3VudF9pZGAgaW50KDExKSBERUZBVUxUIE5VTEwsDQogIGBhcHBfaWRgIGludCgxMSkgREVGQVVMVCBOVUxMLA0KICBgZXhwaXJlc19vbmAgVElNRVNUQU1QIE5VTEwgREVGQVVMVCBOVUxMLA0KICBgYWNjZXNzX3Rva2VuYCB2YXJjaGFyKDI1MDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGFjY2Vzc190b2tlbl9zZWNyZXRgIHZhcmNoYXIoNzUwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGByZWZyZXNoX3Rva2VuYCB2YXJjaGFyKDEwMDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTA0KKSBDSEFSU0VUPXV0ZjhtYjQgQ09MTEFURT11dGY4bWI0X3VuaWNvZGVfY2kgUk9XX0ZPUk1BVD1DT01QQUNUOw0KDQpEUk9QIFRBQkxFIElGIEVYSVNUUyBge3RhYmxlcHJlZml4fWFjY291bnRfbm9kZXNgOw0KQ1JFQVRFIFRBQkxFIGB7dGFibGVwcmVmaXh9YWNjb3VudF9ub2Rlc2AgKA0KICBgaWRgIGludCgxMSkgTk9UIE5VTEwsDQogIGB1c2VyX2lkYCBpbnQoMTEpIERFRkFVTFQgTlVMTCwNCiAgYGFjY291bnRfaWRgIGludCgxMSkgREVGQVVMVCBOVUxMLA0KICBgbm9kZV90eXBlYCB2YXJjaGFyKDIwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBub2RlX2lkYCB2YXJjaGFyKDMwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBhY2Nlc3NfdG9rZW5gIHZhcmNoYXIoMTAwMCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgbmFtZWAgdmFyY2hhcigzNTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGFkZGVkX2RhdGVgIHRpbWVzdGFtcCBOVUxMIERFRkFVTFQgQ1VSUkVOVF9USU1FU1RBTVAsDQogIGBjYXRlZ29yeWAgdmFyY2hhcigyNTUpIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGZhbl9jb3VudGAgYmlnaW50KDIwKSBERUZBVUxUIE5VTEwsDQogIGBpc19hY3RpdmVgIHRpbnlpbnQoMSkgREVGQVVMVCAnMCcsDQogIGBjb3ZlcmAgdmFyY2hhcig3NTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGRyaXZlcmAgdmFyY2hhcig1MCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgc2NyZWVuX25hbWVgIHZhcmNoYXIoMzUwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwNCikgQ0hBUlNFVD11dGY4bWI0IENPTExBVEU9dXRmOG1iNF91bmljb2RlX2NpIFJPV19GT1JNQVQ9Q09NUEFDVDsNCg0KRFJPUCBUQUJMRSBJRiBFWElTVFMgYHt0YWJsZXByZWZpeH1hcHBzYDsNCkNSRUFURSBUQUJMRSBge3RhYmxlcHJlZml4fWFwcHNgICgNCiAgYGlkYCBpbnQoMTEpIE5PVCBOVUxMLA0KICBgdXNlcl9pZGAgaW50KDExKSBERUZBVUxUIE5VTEwsDQogIGBkcml2ZXJgIHZhcmNoYXIoNTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGFwcF9pZGAgdmFyY2hhcigyMDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGFwcF9zZWNyZXRgIHZhcmNoYXIoMjAwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBhcHBfa2V5YCB2YXJjaGFyKDIwMCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgYXBwX2F1dGhlbnRpY2F0ZV9saW5rYCB2YXJjaGFyKDIwMDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGlzX3B1YmxpY2AgdGlueWludCgxKSBERUZBVUxUIE5VTEwsDQogIGBuYW1lYCB2YXJjaGFyKDI1NSkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgaXNfc3RhbmRhcnRgIHRpbnlpbnQoMSkgREVGQVVMVCAnMCcNCikgQ0hBUlNFVD11dGY4bWI0IENPTExBVEU9dXRmOG1iNF91bmljb2RlX2NpIFJPV19GT1JNQVQ9Q09NUEFDVDsNCg0KRFJPUCBUQUJMRSBJRiBFWElTVFMgYHt0YWJsZXByZWZpeH1mZWVkc2A7DQpDUkVBVEUgVEFCTEUgYHt0YWJsZXByZWZpeH1mZWVkc2AgKA0KICBgaWRgIGludCgxMSkgTk9UIE5VTEwsDQogIGBwb3N0X3R5cGVgIHZhcmNoYXIoNTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYHBvc3RfaWRgIGludCgxMSkgREVGQVVMVCBOVUxMLA0KICBgbm9kZV9pZGAgaW50KDExKSBERUZBVUxUIE5VTEwsDQogIGBub2RlX3R5cGVgIHZhcmNoYXIoNDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGRyaXZlcmAgdmFyY2hhcig1MCkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgaXNfc2VuZGVkYCB0aW55aW50KDEpIERFRkFVTFQgJzAnLA0KICBgc3RhdHVzYCB2YXJjaGFyKDE1KSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBlcnJvcl9tc2dgIHZhcmNoYXIoMzAwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBzZW5kX3RpbWVgIHRpbWVzdGFtcCBOVUxMIERFRkFVTFQgQ1VSUkVOVF9USU1FU1RBTVAsDQogIGBpbnRlcnZhbGAgaW50KDExKSBERUZBVUxUIE5VTEwsDQogIGBkcml2ZXJfcG9zdF9pZGAgdmFyY2hhcig0NSkgQ09MTEFURSB1dGY4bWI0X3VuaWNvZGVfY2kgREVGQVVMVCBOVUxMLA0KICBgdmlzaXRfY291bnRgIGludCgxMSkgREVGQVVMVCAnMCcsDQogIGBmZWVkX3R5cGVgIHZhcmNoYXIoNTApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYHNjaGVkdWxlX2lkYCBpbnQoMTEpIERFRkFVTFQgTlVMTCwNCiAgYGRyaXZlcl9wb3N0X2lkMmAgdmFyY2hhcigyNTUpIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTA0KKSBDSEFSU0VUPXV0ZjhtYjQgQ09MTEFURT11dGY4bWI0X3VuaWNvZGVfY2kgUk9XX0ZPUk1BVD1DT01QQUNUOw0KDQpEUk9QIFRBQkxFIElGIEVYSVNUUyBge3RhYmxlcHJlZml4fXNjaGVkdWxlc2A7DQpDUkVBVEUgVEFCTEUgYHt0YWJsZXByZWZpeH1zY2hlZHVsZXNgICgNCiAgYGlkYCBpbnQoMTEpIE5PVCBOVUxMLA0KICBgdXNlcl9pZGAgaW50KDExKSBERUZBVUxUIE5VTEwsDQogIGB0aXRsZWAgdmFyY2hhcigyNTUpIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYHN0YXJ0X2RhdGVgIGRhdGUgREVGQVVMVCBOVUxMLA0KICBgZW5kX2RhdGVgIGRhdGUgREVGQVVMVCBOVUxMLA0KICBgaW50ZXJ2YWxgIGludCgxMSkgREVGQVVMVCBOVUxMLA0KICBgc3RhdHVzYCB2YXJjaGFyKDUwKSBDT0xMQVRFIHV0ZjhtYjRfdW5pY29kZV9jaSBERUZBVUxUIE5VTEwsDQogIGBmaWx0ZXJzYCB2YXJjaGFyKDIwMDApIENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpIERFRkFVTFQgTlVMTCwNCiAgYGFjY291bnRzYCB0ZXh0IENPTExBVEUgdXRmOG1iNF91bmljb2RlX2NpLA0KICBgaW5zZXJ0X2RhdGVgIHRpbWVzdGFtcCBOVUxMIERFRkFVTFQgQ1VSUkVOVF9USU1FU1RBTVAsDQogIGBzaGFyZV90aW1lYCB0aW1lIERFRkFVTFQgTlVMTA0KKSBDSEFSU0VUPXV0ZjhtYjQgQ09MTEFURT11dGY4bWI0X3VuaWNvZGVfY2kgUk9XX0ZPUk1BVD1DT01QQUNUOw0KDQoNCkFMVEVSIFRBQkxFIGB7dGFibGVwcmVmaXh9YWNjb3VudHNgIEFERCBQUklNQVJZIEtFWSAoYGlkYCkgVVNJTkcgQlRSRUU7DQoNCkFMVEVSIFRBQkxFIGB7dGFibGVwcmVmaXh9YWNjb3VudF9hY2Nlc3NfdG9rZW5zYCBBREQgUFJJTUFSWSBLRVkgKGBpZGApIFVTSU5HIEJUUkVFOw0KDQpBTFRFUiBUQUJMRSBge3RhYmxlcHJlZml4fWFjY291bnRfbm9kZXNgIEFERCBQUklNQVJZIEtFWSAoYGlkYCkgVVNJTkcgQlRSRUU7DQoNCkFMVEVSIFRBQkxFIGB7dGFibGVwcmVmaXh9YXBwc2AgQUREIFBSSU1BUlkgS0VZIChgaWRgKSBVU0lORyBCVFJFRTsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1mZWVkc2AgQUREIFBSSU1BUlkgS0VZIChgaWRgKSBVU0lORyBCVFJFRTsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1zY2hlZHVsZXNgIEFERCBQUklNQVJZIEtFWSAoYGlkYCkgVVNJTkcgQlRSRUU7DQoNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1hY2NvdW50c2AgTU9ESUZZIGBpZGAgaW50KDExKSBOT1QgTlVMTCBBVVRPX0lOQ1JFTUVOVDsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1hY2NvdW50X2FjY2Vzc190b2tlbnNgIE1PRElGWSBgaWRgIGludCgxMSkgTk9UIE5VTEwgQVVUT19JTkNSRU1FTlQ7DQoNCkFMVEVSIFRBQkxFIGB7dGFibGVwcmVmaXh9YWNjb3VudF9ub2Rlc2AgTU9ESUZZIGBpZGAgaW50KDExKSBOT1QgTlVMTCBBVVRPX0lOQ1JFTUVOVDsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1hcHBzYCBNT0RJRlkgYGlkYCBpbnQoMTEpIE5PVCBOVUxMIEFVVE9fSU5DUkVNRU5ULCBBVVRPX0lOQ1JFTUVOVD0xMjsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1mZWVkc2AgTU9ESUZZIGBpZGAgaW50KDExKSBOT1QgTlVMTCBBVVRPX0lOQ1JFTUVOVDsNCg0KQUxURVIgVEFCTEUgYHt0YWJsZXByZWZpeH1zY2hlZHVsZXNgIE1PRElGWSBgaWRgIGludCgxMSkgTk9UIE5VTEwgQVVUT19JTkNSRU1FTlQ7DQoNCklOU0VSVCBJTlRPIGB7dGFibGVwcmVmaXh9YXBwc2AgKGBpZGAsIGB1c2VyX2lkYCwgYGRyaXZlcmAsIGBhcHBfaWRgLCBgYXBwX3NlY3JldGAsIGBhcHBfa2V5YCwgYGFwcF9hdXRoZW50aWNhdGVfbGlua2AsIGBpc19wdWJsaWNgLCBgbmFtZWAsIGBpc19zdGFuZGFydGApIFZBTFVFUw0KKDEsIDAsICdmYicsICc2NjI4NTY4Mzc5JywgJ2MxZTYyMGZhNzA4YTFkNTY5NmZiOTkxYzFiZGU1NjYyJywgJzNlN2M3OGUzNWE3NmE5Mjk5MzA5ODg1MzkzYjAyZDk3JywgTlVMTCwgMSwgJ0ZhY2Vib29rIGZvciBpUGhvbmUnLCAyKSwNCigyLCAwLCAnZmInLCAnMzUwNjg1NTMxNzI4JywgJzYyZjhjZTlmNzRiMTJmODRjMTIzY2MyMzQzN2E0YTMyJywgJzg4MmE4NDkwMzYxZGE5ODcwMmJmOTdhMDIxZGRjMTRkJywgTlVMTCwgMSwgJ0ZhY2Vib29rIGZvciBBbmRyb2lkJywgMiksDQooMywgTlVMTCwgJ2ZiJywgJzE5MzI3ODEyNDA0ODgzMycsIE5VTEwsIE5VTEwsICdodHRwczovL3d3dy5mYWNlYm9vay5jb20vdjIuOC9kaWFsb2cvb2F1dGg\/cmVkaXJlY3RfdXJpPWZiY29ubmVjdDovL3N1Y2Nlc3Mmc2NvcGU9ZW1haWwscGFnZXNfc2hvd19saXN0LHB1YmxpY19wcm9maWxlLHVzZXJfYmlydGhkYXkscHVibGlzaF9hY3Rpb25zLG1hbmFnZV9wYWdlcyxwdWJsaXNoX3BhZ2VzLHVzZXJfbWFuYWdlZF9ncm91cHMmcmVzcG9uc2VfdHlwZT10b2tlbixjb2RlJmNsaWVudF9pZD0xOTMyNzgxMjQwNDg4MzMnLCAxLCAnSFRDIFNlbnNlJywgMyksDQooNCwgTlVMTCwgJ2ZiJywgJzE0NTYzNDk5NTUwMTg5NScsIE5VTEwsIE5VTEwsICdodHRwczovL3d3dy5mYWNlYm9vay5jb20vdjEuMC9kaWFsb2cvb2F1dGg\/cmVkaXJlY3RfdXJpPWh0dHBzOi8vd3d3LmZhY2Vib29rLmNvbS9jb25uZWN0L2xvZ2luX3N1Y2Nlc3MuaHRtbCZzY29wZT1lbWFpbCxwYWdlc19zaG93X2xpc3QscHVibGljX3Byb2ZpbGUsdXNlcl9iaXJ0aGRheSxwdWJsaXNoX2FjdGlvbnMsbWFuYWdlX3BhZ2VzLHB1Ymxpc2hfcGFnZXMsdXNlcl9tYW5hZ2VkX2dyb3VwcyZyZXNwb25zZV90eXBlPXRva2VuLGNvZGUmY2xpZW50X2lkPTE0NTYzNDk5NTUwMTg5NScsIDEsICdHcmFwaCBBUEkgZXhwbG9yZXInLCAzKSwNCig1LCBOVUxMLCAnZmInLCAnMTc0ODI5MDAzMzQ2JywgTlVMTCwgTlVMTCwgJ2h0dHBzOi8vd3d3LmZhY2Vib29rLmNvbS92MS4wL2RpYWxvZy9vYXV0aD9yZWRpcmVjdF91cmk9aHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL2Nvbm5lY3QvbG9naW5fc3VjY2Vzcy5odG1sJnNjb3BlPWVtYWlsLHBhZ2VzX3Nob3dfbGlzdCxwdWJsaWNfcHJvZmlsZSx1c2VyX2JpcnRoZGF5LHB1Ymxpc2hfYWN0aW9ucyxtYW5hZ2VfcGFnZXMscHVibGlzaF9wYWdlcyx1c2VyX21hbmFnZWRfZ3JvdXBzJnJlc3BvbnNlX3R5cGU9dG9rZW4mY2xpZW50X2lkPTE3NDgyOTAwMzM0NicsIDEsICdTcG90aWZ5JywgMyksDQooNiwgTlVMTCwgJ3R3aXR0ZXInLCBOVUxMLCAneHE1bkoyZ2tKRlVkcm84ekFXUGxiT09NUHZDR0w3T3VlN2JLeVBGdlBFazFCb3pIWmUnLCAnbDBmT3FNVGdFdE85VVpjSEhWQnhqQnpDTicsIE5VTEwsIE5VTEwsICdGUyBQb3N0ZXIgLSBTdGFuZGFyZCBBUFAnLCAxKSwNCig3LCBOVUxMLCAnbGlua2VkaW4nLCAnODY5ZDBrMGRuejZhbmknLCAnc3ZEOVNTTWdvUjBONHI3RycsIE5VTEwsIE5VTEwsIE5VTEwsICdGUyBQb3N0ZXIgLSBTdGFuZGFyZCBBUFAnLCAxKSwNCig4LCBOVUxMLCAndmsnLCAnNjYwMjYzNCcsICd3YTJpakhlWm40am9wNGxwQ2lHNycsIE5VTEwsIE5VTEwsIE5VTEwsICdGUyBQb3N0ZXIgLSBTdGFuZGFyZCBBUFAnLCAxKSwNCig5LCBOVUxMLCAncGludGVyZXN0JywgJzQ5NzgxMjczNjE0NjQ2MTQ4NjQnLCAnMjBlYTM1ZTYyYjg2ZmUzOWYyYzkxMTE5MmYyM2QzMmE5YTc3ODA1MmRiNmExNWU3ZDI5NzQ2ZjRlMTMyM2I0ZCcsIE5VTEwsIE5VTEwsIE5VTEwsICdGUyBQb3N0ZXIgLSBTdGFuZGFyZCBBUFAnLCAxKSwNCigxMCwgTlVMTCwgJ3JlZGRpdCcsICd3bFlvdkI1dkdiV1lfdycsICc2aUtWTnlLZTNLektiMmhtS3ZNbk1PZXFjbVEnLCBOVUxMLCBOVUxMLCBOVUxMLCAnRlMgUG9zdGVyIC0gU3RhbmRhcmQgQVBQJywgMSksDQooMTEsIE5VTEwsICd0dW1ibHInLCAnJywgJ1kxU3I3SlBxMzJBT21kbHo0Y3N6d0NMRjFENmNVbE5HcHNselduR0x5dExCQkwyY0lzJywgJ2RFVmxUM3dXaWNiQlpNNmZ5QW1rcjQzRHJ2NzA1YmsxVUxlSUU4a0ZEZlNpbE9vSE1HJywgTlVMTCwgTlVMTCwgJ0ZTIFBvc3RlciAtIFN0YW5kYXJkIEFQUCcsIDEpOw0K"}';

		if ( empty( $api_result ) )
		{
			Helper::response( FALSE, fsp__( 'Your server can not access our license server via CURL! Our license server is "%s". Please contact your hosting provider/server administrator and ask them to solve the problem. If you are sure that problem is not your server/hosting side then contact FS Poster administrators.', [ htmlspecialchars( FS_API_URL ) ] ) );
		}

		$result = json_decode( $api_result, TRUE );

		if ( ! is_array( $result ) )
		{
			Helper::response( FALSE, fsp__( 'Reactivation failed! Response: %s', [ htmlspecialchars( $api_result ) ] ) );
		}

		if ( ! ( $result[ 'status' ] === 'ok' && isset( $result[ 'sql' ] ) ) )
		{
			Helper::response( FALSE, isset( $result[ 'error_msg' ] ) ? $result[ 'error_msg' ] : fsp__( 'Error! Response: %s', [ htmlspecialchars( $api_result ) ] ) );
		}

		Helper::setOption( 'plugin_disabled', '0', TRUE );
		Helper::setOption( 'plugin_alert', '', TRUE );
		Helper::setOption( 'poster_plugin_installed', Helper::getVersion(), TRUE );
		Helper::setOption( 'poster_plugin_purchase_key', $code, TRUE );

		Helper::response( TRUE );
	}

	public static function updatePlugin ( $code )
	{
		set_time_limit( 0 );

		register_uninstall_hook( FS_ROOT_DIR . '/init.php', [ Helper::class, 'removePlugin' ] );

		$checkPurchaseCodeURL = FS_API_URL . "api.php?act=update&version1=" . Helper::getInstalledVersion() . "&version2=" . Helper::getVersion() . "&purchase_code=" . $code . "&domain=" . network_site_url();
		$result2              = Curl::getURL( $checkPurchaseCodeURL );

		$result = json_decode( $result2, TRUE );

		if ( ! is_array( $result ) )
		{
			if ( empty( $result2 ) )
			{
				return [
					FALSE,
					fsp__( 'Your server can not access our license server via CURL! Our license server is "%s". Please contact your hosting provider/server administrator and ask them to solve the problem. If you are sure that problem is not your server/hosting side then contact FS Poster administrators.', [ htmlspecialchars( FS_API_URL ) ] )
				];
			}

			return [ FALSE, fsp__( 'Installation error! Response error! Response: %s', [ htmlspecialchars( $result2 ) ] ) ];
		}

		if ( ! ( $result[ 'status' ] === 'ok' && isset( $result[ 'sql' ] ) ) )
		{
			return [
				FALSE,
				isset( $result[ 'error_msg' ] ) ? $result[ 'error_msg' ] : 'Error! Response: ' . htmlspecialchars( $result2 )
			];
		}

		$sql = str_replace( [
			'{tableprefix}',
			'{tableprefixbase}'
		], [
			( DB::DB()->base_prefix . DB::PLUGIN_DB_PREFIX ),
			DB::DB()->base_prefix
		], base64_decode( $result[ 'sql' ] ) );

		foreach ( explode( ';', $sql ) as $sqlQueryOne )
		{
			$checkIfEmpty = preg_replace( '/\s/', '', $sqlQueryOne );
			if ( ! empty( $checkIfEmpty ) )
			{
				DB::DB()->query( $sqlQueryOne );
			}
		}

		Helper::setOption( 'poster_plugin_installed', Helper::getVersion(), TRUE );
		Helper::setOption( 'poster_plugin_purchase_key', $code, TRUE );

		return [ TRUE ];
	}
}